// The quotes: philosophers and the thinkers near them, one a day, in a fixed rotation by day of year.
// [quote, author, work]. Kept short and well attested; no aggregator, no Elvis.
export default [
  ['The impediment to action advances action. What stands in the way becomes the way.', 'Marcus Aurelius', 'Meditations'],
  ['Waste no more time arguing what a good man should be. Be one.', 'Marcus Aurelius', 'Meditations'],
  ['You have power over your mind, not outside events. Realize this, and you will find strength.', 'Marcus Aurelius', 'Meditations'],
  ['Confine yourself to the present.', 'Marcus Aurelius', 'Meditations'],
  ['Very little is needed to make a happy life; it is all within yourself, in your way of thinking.', 'Marcus Aurelius', 'Meditations'],
  ['If it is not right, do not do it; if it is not true, do not say it.', 'Marcus Aurelius', 'Meditations'],
  ['It is not that we have a short time to live, but that we waste a lot of it.', 'Seneca', 'On the Shortness of Life'],
  ['We suffer more often in imagination than in reality.', 'Seneca', 'Letters to Lucilius'],
  ['Begin at once to live, and count each separate day as a separate life.', 'Seneca', 'Letters to Lucilius'],
  ['He who is brave is free.', 'Seneca', 'Letters to Lucilius'],
  ['First say to yourself what you would be; and then do what you have to do.', 'Epictetus', 'Discourses'],
  ['It is not things that disturb us, but our judgements about things.', 'Epictetus', 'Enchiridion'],
  ['No man is free who is not master of himself.', 'Epictetus', 'Discourses'],
  ['Well begun is half done.', 'Aristotle', ''],
  ['We are what we repeatedly do. Excellence, then, is not an act but a habit.', 'Will Durant, on Aristotle', 'The Story of Philosophy'],
  ['The unexamined life is not worth living.', 'Socrates', 'Plato, Apology'],
  ['I know that I know nothing.', 'Socrates', 'Plato, Apology'],
  ['The beginning is the most important part of the work.', 'Plato', 'Republic'],
  ['No man steps in the same river twice.', 'Heraclitus', ''],
  ['Character is destiny.', 'Heraclitus', ''],
  ['Much learning does not teach understanding.', 'Heraclitus', ''],
  ['Real knowledge is to know the extent of one’s ignorance.', 'Confucius', 'Analects'],
  ['A journey of a thousand miles begins with a single step.', 'Laozi', 'Tao Te Ching'],
  ['Knowing others is intelligence; knowing yourself is true wisdom.', 'Laozi', 'Tao Te Ching'],
  ['Not to be able to bear poverty is a shameful thing, but not to know how to chase it away by work is more shameful.', 'Pericles', 'Thucydides'],
  ['Wealth consists not in having great possessions, but in having few wants.', 'Epictetus', ''],
  ['The whole of life is but a moment of time. It is our duty, therefore, to use it, not to misuse it.', 'Plutarch', ''],
  ['Nothing is enough for the man to whom enough is too little.', 'Epicurus', ''],
  ['Do not spoil what you have by desiring what you have not.', 'Epicurus', ''],
  ['The more we do, the more we can do.', 'William Hazlitt', ''],
  ['He who has a why to live can bear almost any how.', 'Friedrich Nietzsche', 'Twilight of the Idols'],
  ['That which does not kill us makes us stronger.', 'Friedrich Nietzsche', 'Twilight of the Idols'],
  ['Become who you are.', 'Friedrich Nietzsche', 'The Gay Science'],
  ['All truly great thoughts are conceived while walking.', 'Friedrich Nietzsche', 'Twilight of the Idols'],
  ['Life can only be understood backwards; but it must be lived forwards.', 'Søren Kierkegaard', 'Journals'],
  ['Anxiety is the dizziness of freedom.', 'Søren Kierkegaard', 'The Concept of Anxiety'],
  ['The function of prayer is not to influence God, but rather to change the nature of the one who prays.', 'Søren Kierkegaard', ''],
  ['Man is condemned to be free.', 'Jean-Paul Sartre', 'Existentialism Is a Humanism'],
  ['One must imagine Sisyphus happy.', 'Albert Camus', 'The Myth of Sisyphus'],
  ['In the depth of winter, I finally learned that within me there lay an invincible summer.', 'Albert Camus', 'Return to Tipasa'],
  ['The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.', 'Albert Camus', ''],
  ['Attention is the rarest and purest form of generosity.', 'Simone Weil', 'Letter to Joë Bousquet'],
  ['Whereof one cannot speak, thereof one must be silent.', 'Ludwig Wittgenstein', 'Tractatus'],
  ['The limits of my language mean the limits of my world.', 'Ludwig Wittgenstein', 'Tractatus'],
  ['Act only according to that maxim whereby you can at the same time will that it should become a universal law.', 'Immanuel Kant', 'Groundwork'],
  ['Science is organized knowledge. Wisdom is organized life.', 'Immanuel Kant', ''],
  ['Dare to know.', 'Immanuel Kant', 'What Is Enlightenment?'],
  ['All our knowledge begins with the senses, proceeds then to the understanding, and ends with reason.', 'Immanuel Kant', 'Critique of Pure Reason'],
  ['I think, therefore I am.', 'René Descartes', 'Discourse on the Method'],
  ['It is not enough to have a good mind; the main thing is to use it well.', 'René Descartes', 'Discourse on the Method'],
  ['All of humanity’s problems stem from man’s inability to sit quietly in a room alone.', 'Blaise Pascal', 'Pensées'],
  ['The heart has its reasons which reason knows nothing of.', 'Blaise Pascal', 'Pensées'],
  ['I have made this letter longer than usual, only because I have not had the time to make it shorter.', 'Blaise Pascal', 'Provincial Letters'],
  ['The greatest thing in the world is to know how to belong to oneself.', 'Michel de Montaigne', 'Essays'],
  ['My life has been full of terrible misfortunes, most of which never happened.', 'Michel de Montaigne', 'Essays'],
  ['I quote others only in order the better to express myself.', 'Michel de Montaigne', 'Essays'],
  ['Do not seek to have events happen as you want them to, but instead want them to happen as they do happen, and your life will go well.', 'Epictetus', 'Enchiridion'],
  ['Nothing is so difficult but that it may be found out by seeking.', 'Terence', ''],
  ['While there’s life, there’s hope.', 'Cicero', 'Letters to Atticus'],
  ['To be ignorant of what occurred before you were born is to remain always a child.', 'Cicero', 'Orator'],
  ['A room without books is like a body without a soul.', 'Cicero', ''],
  ['The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.', 'John Milton', 'Paradise Lost'],
  ['The price of anything is the amount of life you exchange for it.', 'Henry David Thoreau', 'Walden'],
  ['Go confidently in the direction of your dreams. Live the life you have imagined.', 'Henry David Thoreau', 'Walden'],
  ['It is not enough to be busy. So are the ants. The question is: what are we busy about?', 'Henry David Thoreau', 'Letter to H. G. O. Blake'],
  ['Finish each day and be done with it. You have done what you could.', 'Ralph Waldo Emerson', 'Letter to his daughter'],
  ['Tomorrow is a new day; begin it well and serenely.', 'Ralph Waldo Emerson', 'Letter to his daughter'],
  ['The reading of all good books is like a conversation with the finest minds of past centuries.', 'René Descartes', 'Discourse on the Method'],
  ['Hell is other people.', 'Jean-Paul Sartre', 'No Exit'],
  ['We do not learn from experience; we learn from reflecting on experience.', 'John Dewey', ''],
  ['Failure is instructive. The person who really thinks learns quite as much from his failures as from his successes.', 'John Dewey', ''],
  ['The good life is one inspired by love and guided by knowledge.', 'Bertrand Russell', 'What I Believe'],
  ['The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts.', 'Bertrand Russell', ''],
  ['To be happy in this world, especially when youth is past, it is necessary to feel oneself not merely an individual whose days are numbered, but part of the stream of life.', 'Bertrand Russell', 'The Conquest of Happiness'],
  ['If you would be a real seeker after truth, it is necessary that at least once in your life you doubt, as far as possible, all things.', 'René Descartes', 'Principles of Philosophy'],
  ['Time is a river of passing events, and strong is its current.', 'Marcus Aurelius', 'Meditations'],
  ['Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.', 'Marcus Aurelius', 'Meditations'],
  ['How much time he gains who does not look to see what his neighbour says or does or thinks.', 'Marcus Aurelius', 'Meditations'],
  ['Difficulties strengthen the mind, as labour does the body.', 'Seneca', 'Letters to Lucilius'],
  ['As is a tale, so is life: not how long it is, but how good it is, is what matters.', 'Seneca', 'Letters to Lucilius'],
  ['Hang on to your youthful enthusiasms; you will be able to use them better when you are older.', 'Seneca', 'Letters to Lucilius'],
  ['The roots of education are bitter, but the fruit is sweet.', 'Aristotle', ''],
  ['Hope is a waking dream.', 'Aristotle', ''],
  ['What is a friend? A single soul dwelling in two bodies.', 'Aristotle', ''],
  ['By three methods we may learn wisdom: first, by reflection, which is noblest; second, by imitation, which is easiest; and third, by experience, which is the bitterest.', 'Confucius', ''],
  ['To know that we know what we know, and to know that we do not know what we do not know, that is true knowledge.', 'Confucius', 'Analects'],
  ['Mastering others is strength. Mastering yourself is true power.', 'Laozi', 'Tao Te Ching'],
  ['What is to give light must endure burning.', 'Viktor Frankl', 'The Doctor and the Soul'],
  ['Those who have a why to live can bear with almost any how.', 'Viktor Frankl, quoting Nietzsche', 'Man’s Search for Meaning'],
  ['A book must be the axe for the frozen sea within us.', 'Franz Kafka', 'Letter to Oskar Pollak'],
  ['Amor fati: let that be my love henceforth.', 'Friedrich Nietzsche', 'The Gay Science'],
  ['Without music, life would be a mistake.', 'Friedrich Nietzsche', 'Twilight of the Idols'],
  ['Whoever fights monsters should see to it that in the process he does not become a monster.', 'Friedrich Nietzsche', 'Beyond Good and Evil'],
];
